{
	"version": 1778280299,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/btnrestarton-sheet0.png",
		"images/btnmenuon-sheet0.png",
		"images/btnmusicon-sheet0.png",
		"images/btnmusicon-sheet1.png",
		"images/btnsoundon-sheet0.png",
		"images/btnsoundon-sheet1.png",
		"images/lastscorefont.png",
		"images/sprite9-sheet0.png",
		"images/sprite9-sheet1.png",
		"images/sprite11-sheet0.png",
		"images/sprite11-sheet1.png",
		"images/sprite12-sheet0.png",
		"images/sprite12-sheet1.png",
		"images/sprite13-sheet0.png",
		"images/sprite13-sheet1.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/gg-sheet0.png",
		"images/gg-sheet1.png",
		"images/gg-sheet2.png",
		"images/vverx-sheet0.png",
		"images/booom-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/twitter-sheet0.png",
		"images/facebook-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite22-sheet1.png",
		"images/sprite16-sheet0.png",
		"images/sprite16-sheet1.png",
		"images/sprite23-sheet0.png",
		"images/gameresultsfont.png",
		"images/sprite24-sheet0.png",
		"images/destore-sheet0.png",
		"images/moregames-sheet0.png",
		"images/effect-sheet0.png",
		"images/hand-sheet0.png",
		"images/icon-sheet0.png",
		"media/monsterkill.ogg",
		"media/sound 147.ogg",
		"media/sound 148.ogg",
		"media/sound 150.ogg",
		"media/sound 151.ogg",
		"media/sound 153.ogg",
		"media/aaa.ogg",
		"media/aaa2.ogg",
		"media/upmon.ogg",
		"media/musicgame.ogg",
		"media/traffik1.ogg",
		"media/traffik2.ogg",
		"media/traffik3.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}